Vector
VladislavSG/first-term pull request #2
Opened 2020-07-01 18:44 UTC by VladislavSG

2020-07-02 07:15 UTC, kt-cpp requested changes

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +    };
[style] зачем ; после методов? + нет отступов между методами

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +        erase(end() - 1);
надо выбрать -- всегда использовать геттеры или только переменные. но лучше 2ое

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +            for (T *i = data_ + size_ - 1; i != data_ - 1; i--)
1. иф бесполезен 2. зачем такая страшная переменная для итерирования? достаточно size, а в теле обращаться к data

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +        return erase(pos, static_cast<T const*>(pos) + 1);
каст не нужен

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +    iterator insert(iterator it, T const& element) {
на лекции говорилось, что достаточно поддерживать перегрузки insert и erase для const_iterator. от этого стоит избавиться

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +    T* alloc_data (size_t count) {
static

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +            return reinterpret_cast<T *>(operator new(count * sizeof(T)));
static_cast

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +            for (auto *i = const_cast<iterator>(first); i != const_cast<iterator>(last); ++i) {
omg что здесь произошло? сделай какой-нибудь метод для чистки буффера по указателю и размеру, это избавит от копипасты по всему файлу

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +                new(j) T(*i);
здесь нет никаких гарантий безопасности

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +    iterator erase(const_iterator first, const_iterator last) {
на самом деле здесь не нужно менять capacity буффера. об этом никто не просит. здесь все проще, чем могло показаться

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +        size_t new_size;
6 строк превращаются в 1 с помощью тернарника

2020-07-02 07:15 UTC, kt-cpp commented on vector/vector.h
> +            for (T* i = to + to_start + count_copied - 1; i != to - 1; i--)
как уже было написано, это копипаста со страшной перменной в цикле

2020-07-02 10:24 UTC, VladislavSG commented on vector/vector.h
> +    };
fixed

2020-07-02 10:24 UTC, VladislavSG commented on vector/vector.h
> +        erase(end() - 1);
теперь только переменные

2020-07-02 10:29 UTC, VladislavSG commented on vector/vector.h
> +            for (T *i = data_ + size_ - 1; i != data_ - 1; i--)
"If" нужен из-за этой страшной переменной, иначе получим nullptr - 1. Переменная такая страшная, чтобы пройтись по всем элементам с конца, а использовать ptrdiff_t только чтобы проверить условие завершения цикла (i = -1) не захотелось. Опыта нет. Сейчас переписал с переменной ptrdiff_t

2020-07-02 10:40 UTC, VladislavSG commented on vector/vector.h
> +        return erase(pos, static_cast<T const*>(pos) + 1);
fix

2020-07-02 10:44 UTC, VladislavSG commented on vector/vector.h
> +    iterator insert(iterator it, T const& element) {
fix

2020-07-02 10:45 UTC, VladislavSG commented on vector/vector.h
> +    T* alloc_data (size_t count) {
fix

2020-07-02 10:45 UTC, VladislavSG commented on vector/vector.h
> +            return reinterpret_cast<T *>(operator new(count * sizeof(T)));
fix

2020-07-02 11:10 UTC, VladislavSG commented on vector/vector.h
> +            for (auto *i = const_cast<iterator>(first); i != const_cast<iterator>(last); ++i) {
fix

2020-07-02 11:14 UTC, VladislavSG commented on vector/vector.h
> +        size_t new_size;
fix

2020-07-02 11:16 UTC, VladislavSG commented on vector/vector.h
> +            for (T* i = to + to_start + count_copied - 1; i != to - 1; i--)
fixed

2020-07-02 11:17 UTC, VladislavSG commented on vector/vector.h
> +                new(j) T(*i);
¯\_(ツ)_/¯

2020-07-02 11:59 UTC, VladislavSG commented on vector/vector.h
> +    iterator erase(const_iterator first, const_iterator last) {
Может быть и не нужно, но я хочу. Хочу чтобы всегда было capacity = O(size)

2020-07-02 12:55 UTC, kt-cpp requested changes
не нажимай resolve на проблемах, пусть это делает препод. я открыл несколько штук, чтобы потом еще раз посмотреть

2020-07-02 12:55 UTC, kt-cpp commented on vector/vector.h
> +    static void save_copy(T const* from, T * &to, size_t to_start, size_t count) {
T * & это who? передача указателя ничего не копирует, ссылка не нужна

2020-07-02 12:55 UTC, kt-cpp commented on vector/vector.h
> +            destruct_all(to, count_copied);
из-за to_start начались проблемы, ты вызываешь destruct не на том месте, забыв сдвиг. но кажется скорее to_start не нужен, можно без него

2020-07-02 12:55 UTC, kt-cpp commented on vector/vector.h
> +        data_ = (other.size_ ? alloc_data(other.size_) : nullptr);
эта логика уже внутри alloc_data

2020-07-02 12:55 UTC, kt-cpp commented on vector/vector.h
> +#include <memory.h>
1. include *.h это на си, мы в плюсах, поэтому memory. 2. тебе точно все эти инклуды нужны?

2020-07-02 12:55 UTC, kt-cpp commented on vector/vector.h
> +                new(i) T(*(i-1));
это все еще плохой код: конст_каст, ручное дергание new и деструкторов, и даже не weak гарантия. если у тебя бросит какой-нибудь new, у тебя элементы вектора разделятся на 2 куска, а посередине будет пустая ячейка. гораздо лучше использовать свапы

2020-07-02 12:55 UTC, kt-cpp commented on vector/vector.h
> +            save_copy(data_ + position, new_data, position + 1, size_ - position);
если бросит, то ты не почистишь new_data, скопированную до этого. удобнее написать так: сделать копирование прошлой даты, пуш_бек, свапы

2020-07-02 12:55 UTC, kt-cpp commented on vector/vector.h
> +        save_copy(data_ + left_count + count_delete, new_data, left_count, right_count);
1. если бросит второе копирование, то результат первого не почистится. 2. зачастую не нужно переаллоцировать буффер. 3. сделай проверку, если отрезок пустой то ничего не делать

2020-07-02 15:28 UTC, VladislavSG commented on vector/vector.h
> +    static void save_copy(T const* from, T * &to, size_t to_start, size_t count) {
T * & это указатель на ссылку, чтобы присвоить data_ nullptr там где это нужно

2020-07-02 15:44 UTC, VladislavSG commented on vector/vector.h
> +            destruct_all(to, count_copied);
именно для этого и добавил to_start, но забыл сдвиг

2020-07-02 15:47 UTC, VladislavSG commented on vector/vector.h
> +        data_ = (other.size_ ? alloc_data(other.size_) : nullptr);
fixed

2020-07-02 21:21 UTC, VladislavSG commented on vector/vector.h
> +#include <memory.h>
fixed

2020-07-02 21:41 UTC, VladislavSG commented on vector/vector.h
> +        save_copy(data_ + left_count + count_delete, new_data, left_count, right_count);
1. Исправил save_copy.
2. Не знаю как без переаллоцирования буффера дать необходимые гарантии. Можно в случае ошибки удалить весь хвост у вектора и по факту это будут слабые гарантии, но это как-то не адекватно. Поэтому сильные гарантии.
3. fixed
4. Исправил: pop_back работал за O(n)

2020-07-02 21:41 UTC, VladislavSG commented on vector/vector.h
> +            save_copy(data_ + position, new_data, position + 1, size_ - position);
Смотрите исправление save_copy. Теперь почистит. Так было задумано изначально

2020-07-02 22:07 UTC, VladislavSG commented on vector/vector.h
> +                new(i) T(*(i-1));
Использование свапов не очевидно для тех кто такой трюк ни разу не проворачивал. Это немного отличается от swap trick который нам рассказывали на лекции.

2020-07-05 20:58 UTC, kt-cpp approved these changes

2020-07-05 20:58 UTC, merged