Bigint
VladislavSG/first-term pull request #3
Opened 2020-07-08 01:09 UTC by VladislavSG

2020-07-08 12:51 UTC, kt-cpp requested changes
* Страдает нейминг
* Местами страдает форматирование: пробелы, экономия на фигурных скобках

2020-07-08 12:51 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (!isPositive(x)) {
Как `uint32_t` может быть не положительным?

2020-07-08 12:51 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer::big_integer(std::string const& str) : big_integer(0) {
Нет обработки ошибок при невалидной строке

2020-07-08 12:51 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    size_t new_size = (digits_.size() > rhs.digits_.size() ? digits_.size() : rhs.digits_.size());
[minor] `std::max`?

2020-07-08 13:25 UTC, VladislavSG commented on bigint/big_integer.cpp
> +    if (!isPositive(x)) {
У этой операции особый смысл. Она эквивалентна знаку числа после каста к int32_t

2020-07-08 13:26 UTC, VladislavSG commented on bigint/big_integer.cpp
> +big_integer::big_integer(std::string const& str) : big_integer(0) {
В тексте задания этого не требовалось, но ничего, я исправлю

2020-09-23 21:36 UTC, kt-cpp requested changes

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.h
> +    big_integer& bit_operation(big_integer const&,
[minor] Зачем эта функция публичная?

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        }
[note] Тут отлично смотрится тернарник

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.h
> +    big_integer& divAbsLongDigitInPlace(uint32_t x);
[minor] Зачем эти функции публичные?

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +           ((data_.back() == 0) == isPositive(data_[data_.size() - 2]))) {
Можешь пояснить это условие?

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (size_t i = buffer.size() - 1; i > 0; --i) {
[minor] У вектора есть для такого `rbegin` и `rend`

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        sprintf(nine_chars, "%09d", buffer[i - 1]);
Кажется в выводе будут ведущие нули

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (bit_count_r) {
[minor] Лучше использовать явные сравнения, а не каст к `bool`

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (bit_count_l) {
[minor] Лучше использовать явные сравнения, а не каст к `bool`

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    size_t new_size = data_.size() + digit_count + (bit_count_l ? 1 : 0);
[minor] Лучше использовать явные сравнения, а не каст к `bool`

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
Это всё точно стоит снижения читабельности кода, я без пояснений не готов валидировать, что тут написано. Взять модули и перемножить их точно не проще?

2020-09-23 21:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            if (divisor.data_.back()) {
[minor] Снова каст числа к `bool`

2020-10-13 10:09 UTC, VladislavSG commented on bigint/big_integer.h
> +    big_integer& divAbsLongDigitInPlace(uint32_t x);
Первые две могут быть полезны для пользователя, а вот третья и правда считаю не нужна, ведь она используется в качестве оптимизации оператора деления.

2020-10-13 10:34 UTC, VladislavSG commented on bigint/big_integer.cpp
> +        sprintf(nine_chars, "%09d", buffer[i - 1]);
Кажется они и должны быть. Простой пример: to_string(5*10^9 + 1) != 51

2020-10-13 10:39 UTC, VladislavSG commented on bigint/big_integer.cpp
> +           ((data_.back() == 0) == isPositive(data_[data_.size() - 2]))) {
Число хранится в дополнении до 2х и знак числа можно определить по последнему биту. Если наше число +2^32, то оно занимает 2 uint32_t, потому что старший бит первого разряда 1, а число положительное.

2020-10-13 11:00 UTC, VladislavSG commented on bigint/big_integer.cpp
> +    }
Сложные алгоритмы требуют сложного кода. Если брать модуль, то нам придётся скопировать второе число полностью.

2020-10-13 11:29 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        sprintf(nine_chars, "%09d", buffer[i - 1]);
![image](https://user-images.githubusercontent.com/67123994/95855090-8b4c7f80-0d60-11eb-84f0-8c8b65f21910.png)
Где?

2020-10-13 11:33 UTC, kt-cpp commented on bigint/big_integer.h
> +    big_integer& divAbsLongDigitInPlace(uint32_t x);
Довольно странно хотеть вычитать со сдвигом публично

2020-10-13 11:38 UTC, kt-cpp commented on bigint/big_integer.h
> +    big_integer& divAbsLongDigitInPlace(uint32_t x);
Вообще разрядность твоих "цифр" является деталью реализации так что быть им публичными нельзя

2020-10-13 12:01 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
А мне смотреть больно

2020-10-13 12:01 UTC, kt-cpp requested changes
Ответил в старые треды

2020-10-13 12:01 UTC, VladislavSG commented on bigint/big_integer.h
> +    big_integer& divAbsLongDigitInPlace(uint32_t x);
Согласен

2020-10-13 12:10 UTC, VladislavSG commented on bigint/big_integer.cpp
> +        sprintf(nine_chars, "%09d", buffer[i - 1]);
Старший разряд обрабатывается отдельно. В цикле проход с разряда, следующего за старшим

2020-10-13 12:11 UTC, kt-cpp approved these changes

2020-10-13 12:11 UTC, merged